export default function Box({ children }) {
    return (
        <div
            className={`
            max-w-full
            rounded-[32px]
            w-[820px]
            h-[580px]
            p-4
            bg-secondary-glass
            flex
            items-center
            border-1
            border-solid
            border-neon-glass
            shadow-neon-glass
            max-md:w-screen
            max-md:h-screen
            max-md:min-h-[768px]
        `}
        >
            <div
                className={`
                flex
                flex-row
                w-full
                h-full
                shadow-neon
                rounded-[50px]
                border-[1px]
                border-solid
                border-neon
                bg-primary
                max-md:flex-col
                `}
            >
                {children}
            </div>
        </div>
    )
}